# Generated by Django 5.2 on 2025-08-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('placehol1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('placehol2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('placehol3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('placehol4', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('placehol5', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('button', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
