# Generated by Django 5.2 on 2025-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('favicon', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('logotext1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('logoimg', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('logotext2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav4', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav5', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav6', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
