# Generated by Django 5.2 on 2025-08-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('addr', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=150, null=True)),
                ('title2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('text1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('link1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('link2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('link3', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title3', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('week1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('shift1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('week2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('shift2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title4', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('text2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('placeholder', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('button', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
