# Generated by Django 5.2 on 2025-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('text', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('design', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
