# Generated by Django 5.2 on 2025-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
