# Generated by Django 5.2 on 2025-08-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_signup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
