# Generated by Django 5.2 on 2025-08-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('name1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('des1', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('more1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('name2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('des2', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('title3', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title4', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title5', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('more2', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
