# Generated by Django 5.2 on 2025-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('slash', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nav2', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
