# Generated by Django 5.2 on 2025-08-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('img1', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('list1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('img2', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('list2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('img3', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('list3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('img4', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('list4', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
