# Generated by Django 5.2 on 2025-08-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinfo',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='list1',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='list2',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='list3',
        ),
        migrations.RemoveField(
            model_name='serviceinfo',
            name='list4',
        ),
    ]
