# Generated by Django 5.2 on 2025-08-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_serviceinfo_img1_remove_serviceinfo_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('list', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
