# Generated by Django 5.2 on 2025-08-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menustart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('home', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('slash', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('menu', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('title1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('title2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('title3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('taka', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
