# Generated by Django 5.2 on 2025-08-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cate2', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
