# Generated by Django 5.2 on 2025-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('nav1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('slash', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('nav6', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('name1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title1', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('title2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('title3', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('title4', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('addr', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
