# Generated by Django 5.2 on 2025-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('email1', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('message', models.TextField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
