# Generated by Django 5.2 on 2025-08-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='name1',
            new_name='name',
        ),
    ]
