# Generated by Django 5.2 on 2025-08-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_email1_form_email_rename_name1_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conlast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hol1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('hol2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('hol3', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('hol4', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('button', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
