# Generated by Django 5.2 on 2025-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testiinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('nav1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('slash', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('nav5', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('name1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('title1', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('title2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('title3', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('click', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
